repos:
  - repo: local
    hooks:
      - id: import_sort
        name: Sort imports
        entry: ruff check --select I --fix .
        language: python
        types: [python]
      - id: unused_import_removal
        name: Remove unused imports
        entry: ruff check --select F401 --fix
        language: python
        types: [python]
      - id: format_code
        name: Format code
        entry: ruff format .
        language: python
        types: [python]
      - id: lint_code
        name: Lint code
        entry: ruff check
        language: python
        types: [python]